twig:
  debug: false

errors:
  display: -1

session:
  secure: true

pages:
  never_cache_twig: false

cache:
  enabled: true
  gzip: true
  allow_webserver_gzip: true

twig:
  cache: true
  debug: false
  auto_reload: false
  undefined_functions: false
  undefined_filters: false
  umask_fix: false

assets:
  css_pipeline: true
  css_pipeline_include_externals: true
  css_pipeline_before_excludes: true
  css_minify: true
  css_rewrite: true
  js_pipeline: true
  js_pipeline_include_externals: true
  js_pipeline_before_excludes: true
  js_minify: true
  enable_asset_timestamp: true
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'

errors:
  display: '0'
  log: true

debugger:
  enabled: false
  shutdown:
    close_connection: true
  twig: false
