title: Default
'@extends':
    type: default
    context: blueprints://pages

form:
  validation: loose

  fields:

    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            header.fold_content:
              ordering@: 2
              type: toggle
              default: 0
              options:
                0: Nein
                1: Ja
              label: Text zusammenklappen (Mehr lesen)
              highlight: 1
              validate:
                type: bool

            header.sidebar:
              type: radio
              label: Sidebar
              default: 'standard'
              options:
                'standard': Standard
                'kontakt, öffnungszeiten': Kontakt, Öffnungszeiten
                'öffnungszeiten, kontakt': Öffnungszeiten, Kontakt
                'öffnungszeiten, kontakt, post-it': Öffnungszeiten, Kontakt, Post-It
