title: Default
'@extends':
    type: default
    context: blueprints://pages

form:
  validation: loose

  fields:

    tabs:
      type: tabs
      active: 1

      fields:
        content:
          fields:
            header.fold_content:
              ordering@: 2
              type: toggle
              default: 0
              options:
                0: Nein
                1: Ja
              label: Text zusammenklappen (Mehr lesen)
              highlight: 1
              validate:
                type: bool

            header.sidebar_links:
              type: array
              label: Links
              placeholder_key: Name
              placeholder_value: Ziel

            header.sidebar:
              type: radio
              label: Sidebar
              default: 'none'
              options:
                'none': 'Keine Sidebar'
                'kontakt': Kontakt
                'termin': Termin
                'termin, öffnungszeiten': Termin, Öffnungszeiten
                'termin, kontakt': Termin, Kontakt
                'termin, öffnungszeiten, kontakt': Termin, Öffnungszeiten, Kontakt
                'termin, öffnungszeiten, kontakt, post-it': Termin, Öffnungszeiten, Kontakt, Post-It
                'öffnungszeiten': Öffnungszeiten
                'öffnungszeiten, kontakt': Öffnungszeiten, Kontakt
                'öffnungszeiten, kontakt, post-it': Öffnungszeiten, Kontakt, Post-It
